### ISSUE TITLE
Install package with auto resolving dependency

### ISSUE THREAD

**Issue by t-sin** [mimium-org/mmmpm#2]
Now `mmmpm install` simply download package from GitHub then place it in `~/.mimium` directory. If a package specified by user depends on the other package, `mmmpm install` must resolve package dependencies and install them automatically.

## TODO

- [ ] package searching facility in the `~/.mimium` directory
- [ ] package installation by version
- [ ] package installation by type e.g. GitHub
- [ ] dependency resolving algorithm
- [ ] `mmmpm install` can install packages automatically by dependencies section in `mmm.toml`
